
#General mod settings
[general]
	#No comment is given
	#Range: > 0
	foliageShaderRange = 40
	#No comment is given
	#Range: > 0
	Thread_Foliage_Process_Delay = 1000
	#No comment is given
	extraGrass = false

