
#General mod settings
[general]
	#No comment is given
	Misc_proxyRenderOverrideEnabled = true
	#No comment is given
	#Range: > 0
	Misc_simBoxRadiusCutoff = 1124
	#No comment is given
	#Range: > 0
	Misc_simBoxRadiusSpawn = 1024
	#No comment is given
	Misc_ForceVanillaCloudsOff = false
	#No comment is given
	#Range: > 0
	Misc_AutoDataSaveIntervalInTicks = 36000
	#No comment is given
	consoleDebug = false
	#No comment is given
	radarCloudDebug = false
	#If true, lets server side do vanilla weather rules, weather2 will only make storms when server side says 'rain' is on
	overcastMode = false
	#Used if overcastMode is off, 1 = lock weather on, 0 = lock weather off, -1 = dont lock anything, let server do whatever
	#Range: > 0
	lockServerWeatherMode = 0
	#How many ticks between cloud particle spawning
	#Range: > 0
	Cloud_ParticleSpawnDelay = 2
	#Distance between cloud formations, not particles, this includes invisible cloudless formations used during partial cloud coverage
	#Range: > 0
	Cloud_Formation_MinDistBetweenSpawned = 300
	#For a second layer of passive non storm progressing cloudOption
	Cloud_Layer1_Enable = false
	#No comment is given
	#Range: > 0
	Cloud_Layer0_Height = 264
	#No comment is given
	#Range: > 0
	Cloud_Layer1_Height = 414
	#Not used at the moment
	#Range: > 0
	Cloud_Layer2_Height = 564
	#How much to randomly change cloud coverage % amount, performed every 10 seconds
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Cloud_Coverage_Random_Change_Amount = 0.05
	#Minimum percent of cloud coverage, supports negative for extended cloudless sky coverage
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Cloud_Coverage_Min_Percent = 4.9E-324
	#Maximum percent of cloud coverage, supports over 100% for extended full cloud sky coverage
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Cloud_Coverage_Max_Percent = 100.0
	#No comment is given
	#Range: > 0
	Thread_Particle_Process_Delay = 400
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	volWindScale = 0.05
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	volWaterfallScale = 0.5
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	volWindTreesScale = 0.5
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	volWindLightningScale = 1.0
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	sirenActivateDistance = 256.0
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	sensorActivateDistance = 256.0
	#No comment is given
	Block_WeatherMachineNoTornadosOrCyclones = false
	#No comment is given
	Block_WeatherMachineNoRecipe = false
	#No comment is given
	Block_SensorNoRecipe = false
	#No comment is given
	Block_SirenNoRecipe = false
	#No comment is given
	Block_SirenManualNoRecipe = false
	#No comment is given
	Block_WindVaneNoRecipe = false
	#No comment is given
	Block_AnemometerNoRecipe = false
	#No comment is given
	Block_WeatherForecastNoRecipe = false
	#No comment is given
	Block_WeatherDeflectorNoRecipe = false
	#No comment is given
	Block_SandLayerNoRecipe = false
	#No comment is given
	Block_SandNoRecipe = false
	#No comment is given
	Item_PocketSandNoRecipe = false
	#Disabling this recipe will keep them from using other recipes since it depends on this item
	Item_WeatherItemNoRecipe = false
	#No comment is given
	Dimension_List_Weather = "minecraft:overworld, tropicraft:tropicraft"
	#No comment is given
	Dimension_List_Clouds = "minecraft:overworld, tropicraft:tropicraft"
	#No comment is given
	Dimension_List_Storms = "minecraft:overworld, tropicraft:tropicraft"
	#No comment is given
	Dimension_List_WindEffects = "minecraft:overworld, tropicraft:tropicraft"
	#No comment is given
	Villager_MoveInsideForStorms = true
	#No comment is given
	#Range: > 0
	Villager_MoveInsideForStorms_Dist = 256
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	shaderParticleRateAmplifier = 3.0
	#No comment is given
	blockBreakingInvokesCancellableEvent = false
	#If true, will cancel vanilla behavior of setting clear weather when the player sleeps, for global overcast mode
	Global_Overcast_Prevent_Rain_Reset_On_Sleep = false
	#Use if you are on a server with weather but want it ALL off client side for performance reasons, overrides basically every client based setting
	Client_PotatoPC_Mode = false
	#Server and client side, Locks down the mod to only do wind, leaves, foliage shader if on, etc. No weather systems, turns overcast mode on
	Aesthetic_Only_Mode = false

