
#General mod settings
[general]
	#No comment is given
	Wind_Particle_leafs = true
	#Currently used for rates of leaf, waterfall, and fire particles
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Wind_Particle_effect_rate = 0.7
	#No comment is given
	Wind_Particle_waterfall = true
	#No comment is given
	Wind_Particle_fire = false
	#Enables or disables all precipitation particle types
	Particle_RainSnow = true
	#No comment is given
	Particle_Rain = false
	#No comment is given
	Particle_Rain_GroundSplash = true
	#No comment is given
	Particle_Rain_DownfallSheet = false
	#No comment is given
	Particle_VanillaAndWeatherOnly = false
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Precipitation_Particle_effect_rate = 0.7
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Sandstorm_Particle_Debris_effect_rate = 0.6
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Sandstorm_Particle_Dust_effect_rate = 0.6

