
#General mod settings
[general]
	#No comment is given
	#Range: > 0
	Storm_OddsTo1OfHighWindWaterSpout = 150
	#No comment is given
	Storm_FlyingBlocksHurt = true
	#No comment is given
	#Range: > 0
	Storm_MaxPerPlayerPerLayer = 20
	#No comment is given
	#Range: > 0
	Storm_Deadly_CollideDistance = 128
	#No comment is given
	#Range: > 0
	Storm_LightningStrikeBaseValueOddsTo1 = 200
	#No comment is given
	Storm_NoRainVisual = false
	#No comment is given
	#Range: > 0
	Storm_MaxRadius = 300
	#No comment is given
	#Range: > 0
	Storm_AllTypes_TickRateDelay = 60
	#No comment is given
	#Range: > 0
	Storm_Rain_WaterBuildUpRate = 10
	#No comment is given
	#Range: > 0
	Storm_Rain_WaterSpendRate = 3
	#No comment is given
	#Range: > 0
	Storm_Rain_WaterBuildUpOddsTo1FromSource = 15
	#No comment is given
	#Range: > 0
	Storm_Rain_WaterBuildUpOddsTo1FromNothing = 100
	#No comment is given
	#Range: > 0
	Storm_Rain_WaterBuildUpOddsTo1FromOvercastRaining = 30
	#No comment is given
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Storm_TemperatureAdjustRate = 0.1
	#No comment is given
	#Range: > 0
	Storm_HailPerTick = 10
	#No comment is given
	#Range: > 0
	Storm_OddsTo1OfOceanBasedStorm = 300
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_HighWind = 90
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_Hail = 80
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_F0_Tornado = 70
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_C0_Cyclone = 70
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_F1_Tornado = 50
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_C1_Cyclone = 50
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_F2_Tornado = 40
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_C2_Cyclone = 40
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_F3_Tornado = 30
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_C3_Cyclone = 30
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_F4_Tornado = 20
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_C4_Cyclone = 20
	#No comment is given
	#Range: > 0
	Storm_PercentChanceOf_F5_Tornado = 10
	#Also known as full blown hurricane
	#Range: > 0
	Storm_PercentChanceOf_C5_Cyclone = 10
	#No comment is given
	#Range: > 0
	Storm_ParticleSpawnDelay = 3
	#No comment is given
	#Range: > 0
	Player_Storm_Deadly_OddsTo1 = 30
	#No comment is given
	#Range: > 0
	Player_Storm_Deadly_TimeBetweenInTicks = 72000
	#No comment is given
	Server_Storm_Deadly_UseGlobalRate = false
	#Used if Server_Storm_Deadly_UseGlobalRate is on, replaces use of Player_Storm_Deadly_OddsTo1
	#Range: > 0
	Server_Storm_Deadly_OddsTo1 = 30
	#Used if Server_Storm_Deadly_UseGlobalRate is on, replaces use of Player_Storm_Deadly_TimeBetweenInTicks
	#Range: > 0
	Server_Storm_Deadly_TimeBetweenInTicks = 72000
	#For areas without the right mix of hot and cold biomes
	#Range: > 0
	Player_Storm_Deadly_OddsTo1_Land_Based = 300
	#For areas without the right mix of hot and cold biomes
	#Range: > 0
	Player_Storm_Deadly_TimeBetweenInTicks_Land_Based = 240000
	#For areas without the right mix of hot and cold biomes
	#Range: > 0
	Server_Storm_Deadly_OddsTo1_Land_Based = 300
	#For areas without the right mix of hot and cold biomes
	#Range: > 0
	Server_Storm_Deadly_TimeBetweenInTicks_Land_Based = 240000
	#No comment is given
	preventServerThunderstorms = true
	#No comment is given
	#Range: > 0
	Lightning_OddsTo1OfFire = 20
	#No comment is given
	#Range: > 0
	Lightning_lifetimeOfFire = 3
	#No comment is given
	#Range: > 0
	Lightning_DistanceToPlayerForEffects = 256
	#No comment is given
	Lightning_StartsFires = false
	#No comment is given
	#Range: > 0
	Storm_Deflector_RadiusOfStormRemoval = 150
	#The minimum stage a storm has to be at to be removed, stages are: 0 = anything, 1 = thunder, 2 = high wind, 3 = hail, 4 = F0/C0, 5 = F1/C1, 6 = F2/C2, 7 = F3/C3, 8 = F4/C4, 9 = F5/C5
	#Range: > 0
	Storm_Deflector_MinStageRemove = 1
	#No comment is given
	Storm_Deflector_RemoveRainstorms = false
	#No comment is given
	Storm_Deflector_RemoveSandstorms = true
	#Minimum amount of visual rain shown when its raining globally during overcast mode
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	Storm_Rain_Overcast_Amount = 0.01
	#No comment is given
	#Range: > 0
	Storm_Rain_Overcast_OddsTo1 = 50
	#No comment is given
	#Range: > 0
	Storm_Rain_OddsTo1 = 150
	#How often in ticks, a rainstorm updates its list of entities under the rainstorm to extinguish. Extinguishes entities under rainclouds when globalOvercast is off. Set to 0 or less to disable
	#Range: > 0
	Storm_Rain_TrackAndExtinguishEntitiesRate = 200

