
#General Settings
[general]

	#Nutrient Levels
	[general.nutrient_levels]
		#Malnourishment value, below which bad effects can occur. (default:1.0)
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_level_malnourished = 1.0
		#Initial nutrient level for new player. (default:50.0
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_initial = 50.0
		#Boundary between low and target, above which good affects can occur. (default:100.0
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_level_low_target = 100.0
		#Boundary between target and high, below which good affects can occur. (default:120.0)
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_level_target_high = 120.0
		#Engorgement value, above which bad affects can occur.(default:170.0)
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_level_engorged = 170.0
		#Maximum nutrient level. nutrients will cap out at this value no matter how much you eat. (default:180.0)
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_level_max = 180.0
		#Nutrient Increment Rate - rate of nutrient increase relative to food saturation and points. (default:1.0)
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_increment_rate = 1.0
		#Nutrient Decay Rate - base rate of nutrient reduction over time relative to player saturation and food level decay. (default:1.0)
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_decay_rate = 1.0
		#Nutrient Loss On Death - number of nutrition point lost from each nutrient on death (bottoms out at initial value). (default:10.0)
		#Range: 0.0 ~ 1.7976931348623157E308
		nutrient_death_loss = 10.0
		#Max food value a single nutrient for a food item can contain. Helps prevent OP food mods from making it impossible to keep nutrients balanced. (default:20.0)
		#Range: 1.0 ~ 1.7976931348623157E308
		nutrient_max_food_value = 20.0

	#Effects
	[general.nutrition_affects]
		#List of nutrients which only give bad effects when engorged, are not required for a balanced diet and do not cause malnourishment when low (default:sugar).
		effect_bad_nutrients = ["sugars"]
		#List of nutrients which only give good effects, are not required for a balanced diet and do not cause engorgement. You can eat as much as you want (default:vegetables).
		effect_good_nutrients = ["vegetables"]

		#Nourished Effects - effects to apply when the player reaches all nutrient targets.
		[general.nutrition_affects.nourished_affects]
			#Max Health - number of health points (1/2 hearts) to add or subtract. (default: 10.0)
			#Range: -40.0 ~ 40.0
			nourished_max_health = 10.0
			#Knockback Resistance - knockback resistance to add. 1.0 is 100%. (default: 0.0)
			#Range: 0.0 ~ 1.0
			nourished_knockback_resistance = 0.0
			#Movement Speed - increase or reduce player movement speed. Speed I is 0.2. Slowness I is -0.15. (default: 0.2)
			#Range: -0.7 ~ 2.0
			nourished_movement_speed = 0.2
			#Attack Damage - increase or reduce attack damage caused by player. Strength I is 0.2. Weakness I is -0.15. (default: 0.2)
			#Range: -2.0 ~ 4.0
			nourished_attack_damage = 0.2
			#Attack Knockback - increase the amount of knockback caused by the player. (default: 0.0)
			#Range: 0.0 ~ 4.0
			nourished_knockback = 0.0
			#Mining Speed - increase or decrease mining speed of the player. Haste I is 0.1. Mining Fatique I is -0.1. (default: 0.1)
			#Range: -4.0 ~ 4.0
			nourished_mining_speed = 0.1

		#Malnourished Effects
		[general.nutrition_affects.malnourished_affects]
			#Max Health - number of health points (1/2 hearts) to add or subtract. (default: -4.0)
			#Range: -40.0 ~ 40.0
			malnourished_max_health = -4.0
			#Knockback Resistance - knockback resistance to add. 1.0 is 100%. (default: 0.0)
			#Range: 0.0 ~ 1.0
			malnourished_knockback_resistance = 0.0
			#Movement Speed - increase or reduce player movement speed. Speed I is 0.2. Slowness I is -0.15. (default: -0.15)
			#Range: -0.7 ~ 2.0
			malnourished_movement_speed = -0.15
			#Attack Damage - increase or reduce attack damage caused by player. Strength I is 0.2. Weakness I is -0.15. (default: -0.15)
			#Range: -2.0 ~ 4.0
			malnourished_attack_damage = -0.15
			#Attack Knockback - increase the amount of knockback caused by the player. (default: 0.0)
			#Range: 0.0 ~ 4.0
			malnourished_knockback = 0.0
			#Mining Speed - increase or decrease mining speed of the player. Haste I is 0.1. Mining Fatique I is -0.1. (default: 0.0)
			#Range: -4.0 ~ 4.0
			malnourished_mining_speed = 0.0

		#Engorged Effects
		[general.nutrition_affects.engorged_affects]
			#Max Health - number of health points (1/2 hearts) to add or subtract. (default: 0.0)
			#Range: -40.0 ~ 40.0
			engorged_max_health = 0.0
			#Knockback Resistance - knockback resistance to add. 1.0 is 100%. (default: 0.0)
			#Range: 0.0 ~ 1.0
			engorged_knockback_resistance = 0.0
			#Movement Speed - increase or reduce player movement speed. Speed I is 0.2. Slowness I is -0.15. (default: -0.15)
			#Range: -0.7 ~ 2.0
			engorged_movement_speed = -0.15
			#Attack Damage - increase or reduce attack damage caused by player. Strength I is 0.2. Weakness I is -0.15. (default: 0.0)
			#Range: -2.0 ~ 4.0
			engorged_attack_damage = 0.0
			#Attack Knockback - increase the amount of knockback caused by the player. (default: 0.0)
			#Range: 0.0 ~ 4.0
			engorged_knockback = 0.0
			#Mining Speed - increase or decrease mining speed of the player. Haste I is 0.1. Mining Fatique I is -0.1. (default: -0.1)
			#Range: -4.0 ~ 4.0
			engorged_mining_speed = -0.1

	#Nutrient for modded foods: Add foods or tags here to add nutrients to the foods.
	#This is usually only needed for raw ingredients. Crafted and cooked foods will get nutrients from recipe ingredients.
	#This can be done with data packs by adding foods to item tags under forge:nutrient/<nutrientName>, but this config is here for convenience.
	#Data packs are required to define new nutrient categories.
	#These configs are additive on top of data packs.
	#Run the command /nutritionalbalance get_unassigned_foods to find any foods that do not have nutrients.
	[general.nutrient_foods]
		#List of vegetables.
		vegetables_item_list = ["#minecraft:flowers", "#forge:vegetables", "#nourish:vegetables", "candylands:pistachio_ice_cream", "farmersrespite:green_tea", "farmersrespite:yellow_tea", "farmersrespite:black_tea", "croptopia:basil", "croptopia:tea", "croptopia:sea_lettuce", "oceansdelight:bowl_of_guardian_soup", "byg:white_puffball_cap", "byg:cooked_white_puffball_cap", "byg:white_puffball_stew", "blue_skies:winter_leaves", "blue_skies:solnut", "blue_skies:cryo_root", "cuisinedelight:meat_with_vegetables", "cuisinedelight:scrambled_egg_and_tomato", "cuisinedelight:seafood_with_vegetables", "cuisinedelight:vegetable_fried_rice", "cuisinedelight:vegetable_pasta", "cuisinedelight:vegetable_platter"]
		#List of carbohydrates.
		carbs_item_list = ["#forge:carbs", "#forge:grain", "#nourish:carbohydrates", "tstp_content:mushroom_t", "candylands:ginger_bread", "cuisinedelight:fried_mushroom", "cuisinedelight:fried_pasta", "cuisinedelight:fried_rice", "cuisinedelight:ham_fried_rice", "cuisinedelight:meat_fried_rice", "cuisinedelight:meat_pasta", "cuisinedelight:mixed_fried_rice", "cuisinedelight:mixed_pasta", "cuisinedelight:seafood_fried_rice", "cuisinedelight:seafood_pasta", "cuisinedelight:vegetable_fried_rice", "cuisinedelight:vegetable_pasta"]
		#List of simple sugars.
		sugars_item_list = ["#nourish:sweets", "candylands:raw_sugar_cod", "candylands:cooked_sugar_cod", "candylands:licorice", "candylands:dextrose", "candylands:gum_drops", "candylands:red_candy_cane", "candylands:green_candy_cane", "candylands:peppermint_candy_cane", "candylands:white_marshmallow", "candylands:pink_marshmallow", "candylands:roasted_marshmallow", "candylands:candy_corn", "candylands:milk_chocolate_bar", "candylands:white_chocolate_bar", "candylands:dark_chocolate_bar", "candylands:waffle", "candylands:chocolate_waffle", "candylands:syrup_waffle", "candylands:jam_waffle", "candylands:vanilla_cresent", "candylands:jaw_breaker_1", "candylands:jam_jar", "candylands:strawberry_ice_cream", "candylands:vanilla_ice_cream", "candylands:chocolate_ice_cream", "candylands:pistachio_ice_cream", "candylands:popsicle", "candylands:strawberry_cakepop", "candylands:vanilla_cakepop", "candylands:chocolate_cakepop", "candylands:strawberry_lollipop", "candylands:lime_lollipop", "candylands:blueberry_lollipop", "candylands:lemon_lollipop", "candylands:orange_lollipop", "candylands:rainbow_lollipop", "candylands:cotton_candy", "candylands:white_candy", "candylands:orange_candy", "candylands:magenta_candy", "candylands:light_blue_candy", "candylands:yellow_candy", "candylands:lime_candy", "candylands:pink_candy", "candylands:gray_candy", "candylands:light_gray_candy", "candylands:cyan_candy", "candylands:purple_candy", "candylands:blue_candy", "candylands:brown_candy", "candylands:green_candy", "candylands:red_candy", "candylands:black_candy", "candylands:green_marshmallow", "candylands:peppermint_candy", "candylands:blue_cotton_candy", "candylands:candied_apple", "candylands:cycle_pop", "candylands:respawn_pop", "candylands:heavenly_pop", "candylands:warped_pop", "candylands:return_pop", "candylands:jaw_breaker_2", "candylands:jaw_breaker_3", "candylands:jaw_breaker_4", "candylands:jaw_breaker_5", "farmersrespite:green_tea", "farmersrespite:yellow_tea", "farmersrespite:black_tea", "farmersrespite:coffee", "candylands:ginger_bread"]
		#List of proteins.
		protein_item_list = ["#forge:protein", "#forge:milk", "#forge:yogurt", "#forge:nuts", "#nourish:protein", "minecraft:rotten_flesh", "blue_skies:fiery_beans", "farmersrespite:coffee", "croptopia:coffee_beans", "croptopia:glowing_calamari", "croptopia:fried_frog_legs", "croptopia:frog_legs", "oceansdelight:tentacles", "oceansdelight:cut_tentacles", "oceansdelight:tentacle_on_a_stick", "oceansdelight:baked_tentacle_on_a_stick", "oceansdelight:guardian_tail", "oceansdelight:cooked_guardian_tail", "oceansdelight:bowl_of_guardian_soup", "oceansdelight:elder_guardian_slab", "oceansdelight:elder_guardian_slice", "oceansdelight:cooked_elder_guardian_slice", "ad_astra:cheese", "naturalist:cooked_egg", "cuisinedelight:fried_meat_and_melon", "cuisinedelight:ham_fried_rice", "cuisinedelight:meat_fried_rice", "cuisinedelight:meat_pasta", "cuisinedelight:meat_platter", "cuisinedelight:meat_with_seafood", "cuisinedelight:meat_with_vegetables", "cuisinedelight:scrambled_egg_and_tomato", "cuisinedelight:seafood_fried_rice", "cuisinedelight:seafood_pasta", "cuisinedelight:seafood_platter", "cuisinedelight:seafood_with_vegetables"]
		#List of fruits.
		fruits_item_list = ["#forge:fruits", "#nourish:fruit", "candylands:jam_waffle", "ecologics:coconut_slice", "candylands:jam_jar", "candylands:strawberry_ice_cream", "candylands:popsicle", "candylands:strawberry_cakepop", "candylands:strawberry_lollipop", "candylands:lime_lollipop", "candylands:blueberry_lollipop", "candylands:lemon_lollipop", "candylands:orange_lollipop", "candylands:candied_apple", "farmersrespite:coffee_berries", "byg:ether_bulbs", "blue_skies:cherry", "blue_skies:scalefruit", "blue_skies:pine_fruit", "blue_skies:crescent_fruit", "blue_skies:brewberry", "blue_skies:pink_brewberry", "blue_skies:black_brewberry", "cuisinedelight:fried_meat_and_melon"]

	#Lunch Box
	[general.lunchbox]
		#Number of inventory slots the lunchbox contains. (default: 5)
		#Range: 1 ~ 9
		lunchbox_slot_count = 5

